name: "pipeline"

on:
  push:
    branches: [main]

concurrency: 
  group: ci-${{github.ref}}
  cancel-in-progress: true

permissions: 
  contents: read
  packages: write

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 22.13
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test: 
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 22.13
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  typecheck: 
    name: Typecheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 22.13
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  build:
    needs: [typecheck, test, lint]
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 22.13
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
  
  docker:
    needs: [build]
    name: Docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
        name: Login to GitHub Container Registry
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        name: Build and push
      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jaru03/pokedex-ci-cd:sha-${{github.sha}}
            ghcr.io/jaru03/pokedex-ci-cd:latest
          
  
  